// Login
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT = 'LOGOUT';

//Application Setting
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

// Accounts
const GET_ACCOUNTS_FETCH = 'GET_ACCOUNTS_FETCH';
const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';

const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

const GET_ACCOUNT_DETAIL_FETCH = 'GET_ACCOUNT_DETAIL_FETCH';
const GET_ACCOUNT_DETAIL_SUCCESS = 'GET_ACCOUNT_DETAIL_SUCCESS';

const GET_ACCOUNT_OWNER_FETCH = 'GET_ACCOUNT_OWNER_FETCH';
const GET_ACCOUNT_OWNER_SUCCESS = 'GET_ACCOUNT_OWNER_SUCCESS';

const GET_ACCOUNT_STATUS_FETCH = 'GET_ACCOUNT_STATUS_FETCH';
const GET_ACCOUNT_STATUS_SUCCESS = 'GET_ACCOUNT_STATUS_SUCCESS';

const GET_ACCOUNT_TYPE_FETCH = 'GET_ACCOUNT_TYPE_FETCH';
const GET_ACCOUNT_TYPE_SUCCESS = 'GET_ACCOUNT_TYPE_SUCCESS';

const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';

const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';

// Attachments
const GET_ATTACHMENTS_FETCH = 'GET_ATTACHMENTS_FETCH';
const GET_ATTACHMENTS_SUCCESS = 'GET_ATTACHMENTS_SUCCESS';

const GET_ATTACHMENT_DETAIL_FETCH = 'GET_ATTACHMENT_DETAIL_FETCH';
const GET_ATTACHMENT_DETAIL_SUCCESS = 'GET_ATTACHMENT_DETAIL_SUCCESS';

const CREATE_ATTACHMENT_REQUEST = 'CREATE_ATTACHMENT_REQUEST';
const CREATE_ATTACHMENT_SUCCESS = 'CREATE_ATTACHMENT_SUCCESS';

const UPDATE_ATTACHMENT_REQUEST = 'UPDATE_ATTACHMENT_REQUEST';
const UPDATE_ATTACHMENT_SUCCESS = 'UPDATE_ATTACHMENT_SUCCESS';

// Contacts
const GET_CONTACTS_FETCH = 'GET_CONTACTS_FETCH';
const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';

const GET_CONTACT_DETAIL_FETCH = 'GET_CONTACT_DETAIL_FETCH';
const GET_CONTACT_DETAIL_SUCCESS = 'GET_CONTACT_DETAIL_SUCCESS';

const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';

const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST';
const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';

// Industry
const GET_INDUSTRY_FETCH = 'GET_INDUSTRY_FETCH';
const GET_INDUSTRY_SUCCESS = 'GET_INDUSTRY_SUCCESS';

// Organization
const GET_ORGANIZATION_FETCH = 'GET_ORGANIZATION_FETCH';
const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';

// Invoice
const GET_INVOICE_STATUS_FETCH = 'GET_INVOICE_STATUS_FETCH';
const GET_INVOICE_STATUS_SUCCESS = 'GET_INVOICE_STATUS_SUCCESS';

//Notes

const CREATE_NOTES_REQUEST = 'CREATE_NOTES_REQUEST';
const CREATE_NOTES_SUCCESS = 'CREATE_NOTES_SUCCESS';

const GET_NOTES_FETCH = 'GET_NOTES_FETCH';
const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';

//Invoice
const GET_INVOICE_FETCH = 'GET_INVOICE_FETCH';
const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';

const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST';
const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';

const GET_INVOICE_DETAIL_FETCH = 'GET_INVOICE_DETAIL_FETCH';
const GET_INVOICE_DETAIL_SUCCESS = 'GET_INVOICE_DETAIL_SUCCESS';

const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';

const UPDATE_INVOICE_REQUEST = 'UPDATE_INVOICE_REQUEST';
const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';

const GET_INVOICE_OWNER_FETCH = 'GET_INVOICE_OWNER_FETCH';
const GET_INVOICE_OWNER_SUCCESS = 'GET_INVOICE_OWNER_SUCCESS';



export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGOUT,
    GET_ACCOUNTS_FETCH,
    GET_ACCOUNT_SUCCESS,
    CREATE_ACCOUNT_REQUEST,
    CREATE_ACCOUNT_SUCCESS,
    GET_ACCOUNT_DETAIL_FETCH,
    GET_ACCOUNT_DETAIL_SUCCESS,
    DELETE_ACCOUNT_REQUEST,
    DELETE_ACCOUNT_SUCCESS,
    UPDATE_ACCOUNT_REQUEST,
    UPDATE_ACCOUNT_SUCCESS,
    GET_ACCOUNT_OWNER_FETCH,
    GET_ACCOUNT_OWNER_SUCCESS,
    GET_ACCOUNT_STATUS_FETCH,
    GET_ACCOUNT_STATUS_SUCCESS,
    GET_ACCOUNT_TYPE_FETCH,
    GET_ACCOUNT_TYPE_SUCCESS,

    GET_ATTACHMENTS_FETCH,
    GET_ATTACHMENTS_SUCCESS,
    GET_ATTACHMENT_DETAIL_FETCH,
    GET_ATTACHMENT_DETAIL_SUCCESS,
    CREATE_ATTACHMENT_REQUEST,
    CREATE_ATTACHMENT_SUCCESS,
    UPDATE_ATTACHMENT_REQUEST,
    UPDATE_ATTACHMENT_SUCCESS,

    GET_CONTACTS_FETCH,
    GET_CONTACTS_SUCCESS,
    GET_CONTACT_DETAIL_FETCH,
    GET_CONTACT_DETAIL_SUCCESS,
    CREATE_CONTACT_REQUEST,
    CREATE_CONTACT_SUCCESS,
    UPDATE_CONTACT_REQUEST,
    UPDATE_CONTACT_SUCCESS,

    GET_INDUSTRY_FETCH,
    GET_INDUSTRY_SUCCESS,

    GET_ORGANIZATION_FETCH,
    GET_ORGANIZATION_SUCCESS,

    GET_INVOICE_STATUS_FETCH,
    GET_INVOICE_STATUS_SUCCESS,
    CREATE_NOTES_REQUEST,
    CREATE_NOTES_SUCCESS,
    GET_NOTES_SUCCESS,
    GET_NOTES_FETCH,

    GET_INVOICE_FETCH,
    GET_INVOICE_SUCCESS,
    GET_INVOICE_DETAIL_FETCH,
    GET_INVOICE_DETAIL_SUCCESS,
    CREATE_INVOICE_REQUEST,
    CREATE_INVOICE_SUCCESS,
    UPDATE_INVOICE_REQUEST,
    UPDATE_INVOICE_SUCCESS,
    DELETE_INVOICE_REQUEST,
    DELETE_INVOICE_SUCCESS,
    GET_INVOICE_OWNER_FETCH,
    GET_INVOICE_OWNER_SUCCESS
};