// Login
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Accounts
const GET_ACCOUNTS_FETCH = 'GET_ACCOUNTS_FETCH';
const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';

const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';

const GET_ACCOUNT_DETAIL_FETCH = 'GET_ACCOUNT_DETAIL_FETCH';
const GET_ACCOUNT_DETAIL_SUCCESS = 'GET_ACCOUNT_DETAIL_SUCCESS';

const GET_ACCOUNT_OWNER_FETCH = 'GET_ACCOUNT_OWNER_FETCH';
const GET_ACCOUNT_OWNER_SUCCESS = 'GET_ACCOUNT_OWNER_SUCCESS';

const GET_ACCOUNT_STATUS_FETCH = 'GET_ACCOUNT_STATUS_FETCH';
const GET_ACCOUNT_STATUS_SUCCESS = 'GET_ACCOUNT_STATUS_SUCCESS';

const GET_ACCOUNT_TYPE_FETCH = 'GET_ACCOUNT_TYPE_FETCH';
const GET_ACCOUNT_TYPE_SUCCESS = 'GET_ACCOUNT_TYPE_SUCCESS';

// Contacts
const GET_CONTACTS_FETCH = 'GET_CONTACTS_FETCH';
const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';

const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';

const GET_CONTACT_DETAIL_FETCH = 'GET_CONTACT_DETAIL_FETCH';
const GET_CONTACT_DETAIL_SUCCESS = 'GET_CONTACT_DETAIL_SUCCESS';

// Industry
const GET_INDUSTRY_FETCH = 'GET_INDUSTRY_FETCH';
const GET_INDUSTRY_SUCCESS = 'GET_INDUSTRY_SUCCESS';

// Invoice
const GET_INVOICE_STATUS_FETCH = 'GET_INVOICE_STATUS_FETCH';
const GET_INVOICE_STATUS_SUCCESS = 'GET_INVOICE_STATUS_SUCCESS';

export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    GET_ACCOUNTS_FETCH,
    GET_ACCOUNT_SUCCESS,
    CREATE_ACCOUNT_REQUEST,
    CREATE_ACCOUNT_SUCCESS,
    GET_ACCOUNT_DETAIL_FETCH,
    GET_ACCOUNT_DETAIL_SUCCESS,
    GET_ACCOUNT_OWNER_FETCH,
    GET_ACCOUNT_OWNER_SUCCESS,
    GET_ACCOUNT_STATUS_FETCH,
    GET_ACCOUNT_STATUS_SUCCESS,
    GET_ACCOUNT_TYPE_FETCH,
    GET_ACCOUNT_TYPE_SUCCESS,
    GET_CONTACTS_FETCH,
    GET_CONTACTS_SUCCESS,
    CREATE_CONTACT_REQUEST,
    CREATE_CONTACT_SUCCESS,
    GET_CONTACT_DETAIL_FETCH,
    GET_CONTACT_DETAIL_SUCCESS,
    GET_INDUSTRY_FETCH,
    GET_INDUSTRY_SUCCESS,
    GET_INVOICE_STATUS_FETCH,
    GET_INVOICE_STATUS_SUCCESS
};